# Generated by Django 5.0.2 on 2024-03-30 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialApp', '0009_friend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='expiration_time',
        ),
    ]
