# Generated by Django 5.0.2 on 2024-04-14 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialApp', '0011_postmedia_delete_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
